name: spotify
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  unicons: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:

    - assets/images/logo.png
    - assets/images/kendrick.jpg
    - assets/images/google.png
    - assets/images/artist1.png
    - assets/images/artist2.png
    - assets/images/artist3.png
    - assets/images/facebook.png
    - assets/images/Frame1.png
    - assets/images/friday.png
    - assets/images/Group25.png
    - assets/images/image4.png
    - assets/images/impaulsive.png
    - assets/images/jack.png
    - assets/images/jcoleFHD.jpg
    - assets/images/kendrick.jpg
    - assets/images/kendrickDamn.jpeg
    - assets/images/kendrickMBS.jpeg
    - assets/images/khalidFs.png
    - assets/images/lilmama.jpg
    - assets/images/momsBasement.png
    - assets/images/protoje.jpg
    - assets/images/protojeSLT.jpg
    - assets/images/savagelevel.jpg
    - assets/images/savara.jpeg
    - assets/images/tedTalk.png
    - assets/images/topHit.png
    - assets/images/wakadinaliVom.jpeg
    - assets/images/yourDiscover.png
    - assets/images/zoza.jpg
    - assets/images/emlBB.jpeg
    - assets/images/getStarted.png

    

